name: nutrient_details
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  soft_edge_blur: ^0.1.3
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  fonts:
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/InterDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/InterDisplay-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/InterDisplay-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/InterDisplay-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/InterDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/InterDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/InterDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/InterDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/InterDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/InterDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/InterDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/InterDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/InterDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/InterDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/InterDisplay-BlackItalic.ttf
          weight: 900
          style: italic

